### ISSUE TITLE
Endereço da carteira do destinatário

### ISSUE THREAD

**Issue by Thhc10** [quan-projects/quan-desktop-wallet#41]
Na wallet desktop, se uma pessoa não adiciona o endereço de envio nos contatos, fica registrado "sem dados" no campo para quem foi enviado.

**Comment by FredericoVillani** [comment]
gerar payID mantém a identificação de destino

**Comment by jamilservicos** [comment]
em blockchain com privacidade como este, os endereços são ocultos por padrão.
Então você não poder ver o endereço de envio é mais que normal, principalmente se a pessoa ativou a mix
