### ISSUE TITLE
erro no AddresssProvider.cpp ao compilar.

### ISSUE THREAD

**Issue by rgrant99** [quan-projects/quan-desktop-wallet#49]
> **src/AddresssProvider.cpp:32:50: error : conversion from 'long int' to 'const QVariant' is ambiguous - request.setAttribute(QNetworkRequest::User, now);**

por favor mude o **'auto now ='**  para **'qlonglong now = '**

**Comment by jamilservicos** [comment]
resolvido na nova versão.
